[package]
name = "ipc-provider"
description = "The provider to interact with IPC"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-channel = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }

log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
cid = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
num-traits = { workspace = true }
num-derive = "0.3.3"
base64 = { workspace = true }
strum = { version = "0.24", features = ["derive"] }
toml = "0.7.2"
url = { workspace = true }
bytes = "1.4.0"
dirs = "5.0"
serde_bytes = "0.11.9"
thiserror = { workspace = true }
hex = { workspace = true }
serde_tuple = "0.5.0"
zeroize = "1.6.0"

ethers-contract = { workspace = true }
ethers = { workspace = true }
fvm_shared = { workspace = true }
fil_actors_runtime = { workspace = true }
fvm_ipld_encoding = { workspace = true }
primitives = { workspace = true }

ipc-identity = { path = "../identity", features = ["with-ethers"] }
ipc-sdk = { workspace = true }
ipc_actors_abis = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
hex = { workspace = true }
indoc = "2.0.0"