[package]
description = "The primitive types for fvm"
edition = "2021"
name = "primitives"
version = "0.1.0"

[dependencies]
fil_actors_runtime = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true , default-features = false}

anyhow = { workspace = true } 
cid = { workspace = true, default-features = false, features = ["serde-codec"]}
hex = { workspace = true }
indexmap = {version = "1.8.0", features = ["serde-1"]}
integer-encoding = { workspace = true, default-features = false}
lazy_static = { workspace = true }
log = { workspace = true }
num-derive = "0.3.3"
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uint = { version = "0.9.3", default-features = false }
