[package]
name = "ipc_ipld_resolver"
version = "0.1.0"
description = "P2P library to resolve IPLD content across IPC subnets."
authors = ["Protocol Labs"]
edition = "2021"
license-file = "LICENSE"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
blake2b_simd = { workspace = true }
bloom = "0.3"
gcra = "0.4"
lazy_static = { workspace = true }
libipld = { workspace = true, default-features = false, features = ["dag-cbor"] }
libp2p = { workspace = true, default-features = false, features = [
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "noise",
  "yamux",
  "tcp",
  "dns",
  "request-response",
  "metrics",
  "tokio",
  "macros",
  "serde",
  "secp256k1",
  "plaintext",
] }
libp2p-bitswap = { workspace = true }
log = { workspace = true }
prometheus = { workspace = true }
quickcheck = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

fvm_ipld_encoding ={ workspace = true }
fvm_shared = { workspace = true, default-features = false, features = ["crypto"], optional = true }
fvm_ipld_blockstore = { workspace = true, optional = true }

ipc-sdk = { workspace = true }

[dev-dependencies]
quickcheck_macros = { workspace = true }
env_logger = { workspace = true }
fvm_ipld_hamt = { workspace = true }

ipc_ipld_resolver = { path = ".", features = ["arb"] }

[features]
default = ["arb", "missing_blocks"]
arb = ["quickcheck", "fvm_shared/arb"]
missing_blocks = ["fvm_ipld_blockstore"]
